---
- name: Process output and generate vars
  template:
    src: templates/bdd_vars.j2
    dest: "{{ role_path }}/files/scripts/vars.py"
    owner: root
    mode: '0644'
  become: false

- name: clean backups
  ansible.builtin.file:
    path: "{{ role_path }}/files/backups"
    state: absent

- name: create backups
  ansible.builtin.file:
    path: "{{ role_path }}/files/backups"
    state: directory
    mode: '0755' # Permisos para el directorio
